import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import InPageNavigation from "./inPageNavigation";
function MatchDetail() {
  let fixedData = {
    matchInfo: {
      matchId: 89675,
      matchDescription: "5th Match",
      matchFormat: "T20",
      matchType: "league",
      complete: true,
      domestic: false,
      matchStartTimestamp: 1711288800000,
      matchCompleteTimestamp: 1711302619411,
      dayNight: false,
      year: 2024,
      state: "complete",
      team1: {
        id: 971,
        name: "Gujarat Titans",
        playerDetails: [
          {
            id: 11808,
            name: "Shubman Gill",
            fullName: "Shubman Gill",
            nickName: "Shubman Gill",
            captain: true,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "GT",
            faceImageId: 352479,
          },
          {
            id: 1465,
            name: "W Saha",
            fullName: "Wriddhiman Saha",
            nickName: "Saha",
            captain: false,
            role: "WK-Batsman",
            keeper: true,
            substitute: false,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "GT",
            faceImageId: 171058,
          },
          {
            id: 13866,
            name: "Sai Sudharsan",
            fullName: "Sai Sudharsan",
            nickName: "Sai Sudharsan",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm leg break",
            teamName: "GT",
            faceImageId: 182026,
            inMatchChange: "MOUT",
          },
          {
            id: 8204,
            name: "Vijay Shankar",
            fullName: "Vijay Shankar",
            nickName: "Shankar",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm medium",
            teamName: "GT",
            faceImageId: 170664,
          },
          {
            id: 6349,
            name: "David Miller",
            fullName: "David Miller",
            nickName: "Miller",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm off break",
            teamName: "GT",
            faceImageId: 351831,
            isOverseas: true,
          },
          {
            id: 13214,
            name: "Azmatullah",
            fullName: "Azmatullah Omarzai",
            nickName: "Azmatullah",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "GT",
            faceImageId: 352438,
            isOverseas: true,
          },
          {
            id: 9693,
            name: "Rahul Tewatia",
            fullName: "Rahul Tewatia",
            nickName: "Rahul Tewatia",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm leg break",
            teamName: "GT",
            faceImageId: 196288,
          },
          {
            id: 10738,
            name: "Rashid Khan",
            fullName: "Rashid Khan",
            nickName: "Rashid Khan",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm leg break",
            teamName: "GT",
            faceImageId: 352439,
            isOverseas: true,
          },
          {
            id: 1858,
            name: "Umesh",
            fullName: "Umesh Yadav",
            nickName: "Umesh Yadav",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast",
            teamName: "GT",
            faceImageId: 332901,
          },
          {
            id: 11595,
            name: "Sai Kishore",
            fullName: "Ravisrinivasan Sai Kishore",
            nickName: "Sai Kishore",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "GT",
            faceImageId: 226507,
          },
          {
            id: 13143,
            name: "Spencer Johnson",
            fullName: "Spencer Johnson",
            nickName: "Spencer Johnson",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Left Arm fast medium",
            teamName: "GT",
            faceImageId: 182026,
            isOverseas: true,
          },
          {
            id: 10520,
            name: "Sharath BR",
            fullName: "Sharath BR",
            nickName: "Sharath BR",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "GT",
            faceImageId: 182026,
            splSubstitute: true,
          },
          {
            id: 8181,
            name: "Mohit Sharma",
            fullName: "Mohit Sharma",
            nickName: "Mohit Sharma",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "GT",
            faceImageId: 192642,
            inMatchChange: "MIN",
            splSubstitute: true,
          },
          {
            id: 10499,
            name: "Abhinav Manohar",
            fullName: "Abhinav Manohar",
            nickName: "Abhinav Manohar",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm leg break",
            teamName: "GT",
            faceImageId: 182026,
            splSubstitute: true,
          },
          {
            id: 15452,
            name: "Noor Ahmad",
            fullName: "Noor Ahmad",
            nickName: "Noor Ahmad",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "GT",
            faceImageId: 352443,
            splSubstitute: true,
            isOverseas: true,
          },
          {
            id: 14596,
            name: "Manav Suthar",
            fullName: "Manav Suthar",
            nickName: "Manav Suthar",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "GT",
            faceImageId: 182026,
            splSubstitute: true,
          },
          {
            id: 11128,
            name: "Joshua Little",
            fullName: "Joshua Little",
            nickName: "Joshua Little",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "GT",
            faceImageId: 244649,
          },
          {
            id: 6326,
            name: "Williamson",
            fullName: "Kane Williamson",
            nickName: "Williamson",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "GT",
            faceImageId: 351812,
          },
          {
            id: 1649,
            name: "Wade",
            fullName: "Matthew Wade",
            nickName: "Wade",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "",
            teamName: "GT",
            faceImageId: 244799,
          },
          {
            id: 8182,
            name: "Jayant Yadav",
            fullName: "Jayant Yadav",
            nickName: "Jayant Yadav",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "GT",
            faceImageId: 226388,
          },
          {
            id: 8944,
            name: "Warrier",
            fullName: "Sandeep Warrier",
            nickName: "Warrier",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm medium",
            teamName: "GT",
            faceImageId: 226336,
          },
          {
            id: 10226,
            name: "Shahrukh Khan",
            fullName: "Shahrukh Khan",
            nickName: "Shahrukh Khan",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "GT",
            faceImageId: 226465,
          },
          {
            id: 12779,
            name: "Darshan Nalkande",
            fullName: "Darshan Nalkande",
            nickName: "Darshan Nalkande",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "GT",
            faceImageId: 182026,
          },
          {
            id: 13136,
            name: "Kartik Tyagi",
            fullName: "Kartik Tyagi",
            nickName: "Kartik Tyagi",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "GT",
            faceImageId: 226311,
          },
          {
            id: 14706,
            name: "Sushant Mishra",
            fullName: "Sushant Mishra",
            nickName: "Sushant Mishra",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Left Arm fast medium",
            teamName: "GT",
            faceImageId: 182026,
          },
          {
            id: 269,
            name: "Ashish Nehra",
            fullName: "Ashish Nehra",
            nickName: "Nehra",
            role: "Head coach",
            teamId: 971,
            teamName: "GT",
            faceImageId: 155112,
            isSupportStaff: true,
          },
          {
            id: 4601,
            name: "Gary Kirsten",
            fullName: "Gary Kirsten",
            nickName: "Kirsten",
            role: "Batting coach and mentor",
            teamId: 971,
            teamName: "GT",
            faceImageId: 157564,
            isSupportStaff: true,
          },
          {
            id: 166,
            name: "Vikram Solanki",
            fullName: "Vikram Solanki",
            nickName: "Solanki",
            role: "Director of Cricket",
            teamId: 971,
            teamName: "GT",
            faceImageId: 182026,
            isSupportStaff: true,
          },
          {
            id: 597,
            name: "Mithun Manhas",
            fullName: "Mithun Manhas",
            nickName: "Manhas",
            role: "Assistant coach",
            teamId: 971,
            teamName: "GT",
            faceImageId: 182026,
            isSupportStaff: true,
          },
          {
            id: 1423951,
            name: "Narender Negi",
            fullName: "Narender Negi",
            nickName: "Narender Negi",
            role: "Assistant coach",
            teamId: 971,
            teamName: "GT",
            faceImageId: 182026,
            isSupportStaff: true,
          },
          {
            id: 3905,
            name: "Aashish Kapoor",
            fullName: "Aashish Kapoor",
            nickName: "Kapoor",
            role: "Assistant coach",
            teamId: 971,
            teamName: "GT",
            faceImageId: 182026,
            isSupportStaff: true,
          },
          {
            id: 1423956,
            name: "Naeem Amin",
            fullName: "Naeem Amin",
            nickName: "Naeem Amin",
            role: "Assistant coach",
            teamId: 971,
            teamName: "GT",
            faceImageId: 182026,
            isSupportStaff: true,
          },
        ],
        shortName: "GT",
      },
      team2: {
        id: 62,
        name: "Mumbai Indians",
        playerDetails: [
          {
            id: 576,
            name: "Rohit",
            fullName: "Rohit Sharma",
            nickName: "Rohit",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "MI",
            faceImageId: 352478,
          },
          {
            id: 10276,
            name: "Ishan Kishan",
            fullName: "Ishan Kishan",
            nickName: "Ishan Kishan",
            captain: false,
            role: "WK-Batsman",
            keeper: true,
            substitute: false,
            teamId: 62,
            battingStyle: "LEFT",
            bowlingStyle: "",
            teamName: "MI",
            faceImageId: 352492,
          },
          {
            id: 14504,
            name: "Tilak Varma",
            fullName: "Tilak Varma",
            nickName: "Tilak Varma",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm off break",
            teamName: "MI",
            faceImageId: 226525,
          },
          {
            id: 36139,
            name: "Naman Dhir",
            fullName: "Naman Dhir",
            nickName: "Naman Dhir",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "MI",
            faceImageId: 182026,
          },
          {
            id: 9647,
            name: "Hardik Pandya",
            fullName: "Hardik Pandya",
            nickName: "Hardik Pandya",
            captain: true,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "MI",
            faceImageId: 352482,
          },
          {
            id: 13169,
            name: "Tim David",
            fullName: "Tim David",
            nickName: "Tim David",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm medium",
            teamName: "MI",
            faceImageId: 244810,
            isOverseas: true,
          },
          {
            id: 13496,
            name: "Shams Mulani",
            fullName: "Shams Mulani",
            nickName: "Shams Mulani",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "MI",
            faceImageId: 182026,
          },
          {
            id: 466,
            name: "Chawla",
            fullName: "Piyush Chawla",
            nickName: "Chawla",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm leg break",
            teamName: "MI",
            faceImageId: 152613,
          },
          {
            id: 13320,
            name: "Gerald Coetzee",
            fullName: "Gerald Coetzee",
            nickName: "Gerald Coetzee",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast",
            teamName: "MI",
            faceImageId: 351631,
            isOverseas: true,
          },
          {
            id: 9311,
            name: "Bumrah",
            fullName: "Jasprit Bumrah",
            nickName: "Bumrah",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast",
            teamName: "MI",
            faceImageId: 352488,
          },
          {
            id: 9821,
            name: "Luke Wood",
            fullName: "Luke Wood",
            nickName: "Wood",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "LEFT",
            bowlingStyle: "Left Arm fast medium",
            teamName: "MI",
            faceImageId: 158044,
            inMatchChange: "MOUT",
            isOverseas: true,
          },
          {
            id: 20538,
            name: "Dewald Brevis",
            fullName: "Dewald Brevis",
            nickName: "Brevis",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm leg break",
            teamName: "MI",
            faceImageId: 226302,
            inMatchChange: "MIN",
            splSubstitute: true,
            isOverseas: true,
          },
          {
            id: 13646,
            name: "Romario Shepherd",
            fullName: "Romario Shepherd",
            nickName: "Shepherd",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "MI",
            faceImageId: 226370,
            splSubstitute: true,
            isOverseas: true,
          },
          {
            id: 11893,
            name: "Vishnu Vinod",
            fullName: "Vishnu Vinod",
            nickName: "Vishnu Vinod",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "MI",
            faceImageId: 182026,
            splSubstitute: true,
          },
          {
            id: 13915,
            name: "Nehal Wadhera",
            fullName: "Nehal Wadhera",
            nickName: "Nehal Wadhera",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm leg break",
            teamName: "MI",
            faceImageId: 182026,
            splSubstitute: true,
          },
          {
            id: 3007,
            name: "Nabi",
            fullName: "Mohammad Nabi",
            nickName: "Nabi",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "MI",
            faceImageId: 352437,
            splSubstitute: true,
            isOverseas: true,
          },
          {
            id: 7915,
            name: "Suryakumar Yadav",
            fullName: "Suryakumar Yadav",
            nickName: "Suryakumar Yadav",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "MI",
            faceImageId: 352481,
          },
          {
            id: 9746,
            name: "Shreyas Gopal",
            fullName: "Shreyas Gopal",
            nickName: "Shreyas Gopal",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm leg break",
            teamName: "MI",
            faceImageId: 226505,
          },
          {
            id: 13747,
            name: "Arjun Tendulkar",
            fullName: "Arjun Tendulkar",
            nickName: "Arjun Tendulkar",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "LEFT",
            bowlingStyle: "Left Arm fast medium",
            teamName: "MI",
            faceImageId: 154048,
          },
          {
            id: 14190,
            name: "Kumar Kartikeya",
            fullName: "Kumar Kartikeya",
            nickName: "Kartikeya",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "MI",
            faceImageId: 327479,
          },
          {
            id: 14408,
            name: "Shivalik Sharma",
            fullName: "Shivalik Sharma",
            nickName: "Shivalik Sharma",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm leg break",
            teamName: "MI",
            faceImageId: 182026,
          },
          {
            id: 14598,
            name: "Anshul Kamboj",
            fullName: "Anshul Kamboj",
            nickName: "Anshul Kamboj",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "MI",
            faceImageId: 182026,
          },
          {
            id: 15727,
            name: "Akash Madhwal",
            fullName: "Akash Madhwal",
            nickName: "Akash Madhwal",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "MI",
            faceImageId: 182026,
          },
          {
            id: 18509,
            name: "N Thushara",
            fullName: "Nuwan Thushara",
            nickName: "N Thushara",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "MI",
            faceImageId: 226338,
          },
          {
            id: 23346,
            name: "Kwena Maphaka",
            fullName: "Kwena Maphaka",
            nickName: "Kwena Maphaka",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "LEFT",
            bowlingStyle: "",
            teamName: "MI",
            faceImageId: 182026,
          },
          {
            id: 208,
            name: "Mark Boucher",
            fullName: "Mark Boucher",
            nickName: "Boucher",
            role: "Head coach",
            teamId: 62,
            teamName: "MI",
            faceImageId: 157815,
            isSupportStaff: true,
          },
          {
            id: 42670,
            name: "James Pamment",
            fullName: "James Pamment",
            nickName: "James Pamment",
            role: "Fielding coach",
            teamId: 62,
            teamName: "MI",
            faceImageId: 182026,
            isSupportStaff: true,
          },
          {
            id: 25,
            name: "Sachin Tendulkar",
            fullName: "Sachin Tendulkar",
            nickName: "Tendulkar",
            role: "ICON",
            teamId: 62,
            teamName: "MI",
            faceImageId: 171004,
            isSupportStaff: true,
          },
          {
            id: 657,
            name: "Kieron Pollard",
            fullName: "Kieron Pollard",
            nickName: "Pollard",
            role: "Batting coach",
            teamId: 62,
            teamName: "MI",
            faceImageId: 226283,
            isSupportStaff: true,
          },
          {
            id: 111,
            name: "Lasith Malinga",
            fullName: "Lasith Malinga",
            nickName: "Malinga",
            role: "Bowling Coach",
            teamId: 62,
            teamName: "MI",
            faceImageId: 170724,
            isSupportStaff: true,
          },
          {
            id: 1805,
            name: "Jagadeesh Arunkumar",
            fullName: "Jagadeesh Arunkumar",
            nickName: "Arunkumar",
            role: "Assistant Batting Coach",
            teamId: 62,
            teamName: "MI",
            faceImageId: 182026,
            isSupportStaff: true,
          },
        ],
        shortName: "MI",
      },
      series: {
        id: 7607,
        name: "Indian Premier League 2024",
        seriesType: "IPL",
        startDate: 1710979200000,
        endDate: 1716768000000,
        seriesFolder: "",
        odiSeriesResult: "",
        t20SeriesResult: "''",
        testSeriesResult: "",
        tournament: true,
      },
      umpire1: {
        id: 8111,
        name: "Vineet Kulkarni",
        country: "IND",
      },
      umpire2: {
        id: 8909,
        name: "Virender Sharma",
        country: "IND",
      },
      umpire3: {
        id: 8862,
        name: "Nitin Menon",
        country: "IND",
      },
      referee: {
        id: 3894,
        name: "Javagal Srinath",
        country: "IND",
      },
      tossResults: {
        tossWinnerId: 62,
        tossWinnerName: "Mumbai Indians",
        decision: "Bowling",
      },
      result: {
        resultType: "win",
        winningTeam: "Gujarat Titans",
        winningteamId: 971,
        winningMargin: 6,
        winByRuns: true,
        winByInnings: false,
      },
      venue: {
        id: 50,
        name: "Narendra Modi Stadium",
        city: "Ahmedabad",
        country: "India",
        timezone: "+05:30",
        latitude: "23.091785",
        longitude: "72.597465",
      },
      status: "Mumbai Indians opt to bowl",
      playersOfTheMatch: [
        {
          id: 13866,
          name: "Sai Sudharsan",
          fullName: "Sai Sudharsan",
          nickName: "Sai Sudharsan",
          captain: false,
          keeper: false,
          substitute: false,
          teamName: "Chepauk Super Gillies",
          faceImageId: 717782,
        },
      ],
      playersOfTheSeries: [],
      revisedTarget: {
        reason: "",
      },
      matchTeamInfo: [
        {
          battingTeamId: 971,
          battingTeamShortName: "GT",
          bowlingTeamId: 62,
          bowlingTeamShortName: "MI",
        },
        {
          battingTeamId: 62,
          battingTeamShortName: "MI",
          bowlingTeamId: 971,
          bowlingTeamShortName: "GT",
        },
      ],
      isMatchNotCovered: false,
      HYSEnabled: 0,
      livestreamEnabled: false,
      isFantasyEnabled: true,
      livestreamEnabledGeo: [
        "MA",
        "KW",
        "EG",
        "TN",
        "JO",
        "MR",
        "US",
        "BH",
        "SD",
        "LY",
        "IQ",
        "SA",
        "MU",
        "AE",
        "LB",
        "DJ",
        "SO",
        "SS",
        "YT",
        "MG",
        "YE",
        "RE",
        "OM",
        "DZ",
        "QA",
        "CA",
        "TD",
        "PS",
      ],
      alertType: "auto",
      shortStatus: "GT won",
      matchImageId: 387732,
    },
    venueInfo: {
      established: 1982,
      capacity: "132,000",
      knownAs: "Motera Gujarat Stadium, Sardar Patel Stadium",
      ends: "Adani Pavilion End, GMDC End",
      city: "Ahmedabad",
      country: "India",
      timezone: "+05:30",
      homeTeam: "Gujarat, Gujarat Titans",
      floodlights: true,
      curator: "Bagira Thakur",
      profile:
        "<b>Introduction:</b>\n\nPopular as one of the premier cricket grounds in India, the stadium is generally known as the 'Motera Stadium' to avoid confusion with another stadium of the same name in the Navrangpura area. It is owned by the Gujarat Cricket Association and comes under the aegis of the West Zone.\n\n<b>Venue History:</b>\n\nBefore this stadium came into existence, international matches were played at the Ahmedabad Municipal Corporation's stadium, bearing the same name. However, in 1982, the Gujrat government donated a 50-acre land on the banks of the Sabarmati river and the Motera stadium was constructed in a span of only nine months. The first international match to be hosted here was a Test between India and West Indies on November 12, 1983. \n\n<b>Venue Description</b>:\n\nThe Motera stadium has been witness to several important landmarks. It is also the adopted home of the Indian Premier League franchise Rajasthan Royals. The current stands are as follows - GMDC Upper and Lower stands, East Upper and Lower Pavilion, Adani Lower Pavilion, Adani Upper Pavilion, Club Pavilion, and West Pavilion. All stands, except the Club and West Pavilions, consistent two tiers. The Adani Pavilion consists of more than 20 air-conditioned corporate boxes as well as the player dressing rooms. The stadium has 21 entry gates. The ground was renovated in 2006, just before the Champions Trophy. After renovation, state-of-the-art floodlights were added to the stadium along with covered stands, three new pitches and a new outfield.\n\n<b>How does the pitch play?</b>\n\nThe Motera offers a slow wicket. Initially, it was a bowler-friendly track but over the course of time, the pitch lost its spice as it started to slow down. Very few Test games have reached a conclusion over here.\n\n<b>Trivia</b>:\n\nSunil Gavaskar became the first-ever cricketer to score 10,000 runs in Test cricket on this ground - a feat he achieved against Pakistan in 1986-87.\n\nKapil Dev claimed his 432nd Test wicket on this ground to become the highest wicket-taker in the world, breaking Sir Richard Hadlee's record in 1993.\n\nby <b>Sonali Dhulap</b>",
      imageUrl:
        "http://i.cricketcb.com/i/stats/fth/540x303/venue/images/50.jpg",
      ground: "Narendra Modi Stadium",
      groundLength: 0,
      groundWidth: 0,
      otherSports: null,
    },
    broadcastInfo: [],
  };
  let { id } = useParams();
  let [data, setData] = useState([]);

  async function FetchMatchDetail() {
    const url = `https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/${id}`;
    const options = {
      method: "GET",
      headers: {
        "X-RapidAPI-Key": import.meta.env.VITE_API_KEY,

        "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com",
      },
    };

    try {
      const response = await fetch(url, options);
      const result = await response.json();
      setData(result);
      //   console.log(result);
    } catch (error) {
      console.error(error);
    }
  }
  // FetchMatchDetail()
  // console.log(id);
  useEffect(() => {
    // FetchMatchDetail()
  }, []);
  return (
    <div className="flex flex-col w-full items-center pt-5">
      <div className="text-2xl py-3 pb-4 font-medium exsm:text-xl">MatchDetail</div>
      <InPageNavigation
        teams={[
          fixedData.matchInfo.team1.shortName,
          fixedData.matchInfo.team2.shortName,
        ]}
      >
        {fixedData.matchInfo.team1.playerDetails.map((player, i) => {
          return <div key={i} className="w-full  pt-2 pl-4">
           <h1 className="font-medium text-[17px] exsm:text-[15px]">{player.fullName}</h1>
           <h1 className="text-[16px] text-black/60 exsm:text-[13px]">{player.role}</h1>
          </div>
          ;
        })}
        {fixedData.matchInfo.team2.playerDetails.map((player, i) => {
          return <div key={i} className="w-full pt-2 pl-4">
          <h1 className="font-medium text-[17px] exsm:text-[15px]" >{player.fullName}</h1>
          <h1 className="text-[16px] text-black/60 exsm:text-[13px]">{player.role}</h1>
         </div>
         ;
        })}
      </InPageNavigation>

      {/* {data.length <= 0 ? (
        <h1>Loading...</h1>
      ) : (
        <InPageNavigation
          teams={[
            fixedData.matchInfo.team1.shortName,
            fixedData.matchInfo.team2.shortName,
          ]}
        ></InPageNavigation>
      )}{" "} */}
    </div>
  );
}

export default MatchDetail;
